'use strict';

// studio-builder.js
// Generates shop.mds.zip + mInbox.zip from Pocket Shop templates.
// Called by studio.js after form submission.
// v2: supports multi-product shops (up to 4 products).

const fs      = require('fs');
const path    = require('path');
const archiver = require('archiver');

const SHOP_TEMPLATE_DIR  = path.join(__dirname, 'pocketshop-shop');
const INBOX_TEMPLATE_DIR = path.join(__dirname, 'mInbox');
const DEFAULT_IMAGE      = path.join(SHOP_TEMPLATE_DIR, 'product.svg');

const USDT_TOKEN_ID = '0x7D39745FBD29049BE29850B55A18BF550E4D442F930F86266E34193D89042A90';
const MINI_TOKEN_ID = '0x00';

function getCurrencyConfig(currency) {
    if (currency === 'USDT') {
        return { label: 'USDT', tokenId: USDT_TOKEN_ID, icon: 'usdt_icon.svg' };
    }
    return { label: 'Minima', tokenId: MINI_TOKEN_ID, icon: 'minima_logo_bw.svg' };
}

function ensureDir(d) { if (!fs.existsSync(d)) fs.mkdirSync(d, { recursive: true }); }
function copyFile(s, d) { if (fs.existsSync(s)) fs.copyFileSync(s, d); }

function zipDir(tmpDir, outPath) {
    return new Promise((resolve, reject) => {
        const output  = fs.createWriteStream(outPath);
        const archive = archiver('zip', { zlib: { level: 9 } });
        output.on('close', () => resolve(archive.pointer()));
        archive.on('error', reject);
        archive.pipe(output);
        archive.directory(tmpDir, false);
        archive.finalize();
    });
}

function generateShopConfig(address, pubkey, shopName) {
    return `// Shop - Vendor Configuration
const VENDOR_PUBLIC_KEY = "${pubkey}";
const VENDOR_ADDRESS = "${address}";

const VENDOR_CONFIG = {
    vendorPublicKey: VENDOR_PUBLIC_KEY,
    vendorAddress: VENDOR_ADDRESS,
    appName: ${JSON.stringify(shopName)},
    version: "2.0.0"
};
`;
}

function generateProductsJs(products, currConfig) {
    const items = products.map((p, i) => {
        return `    { id: "product-${i}", name: ${JSON.stringify(p.name)}, description: ${JSON.stringify(p.description || '')}, price: ${p.price}, maxUnits: ${p.maxUnits || 10}, image: "product-${i}${p._imageExt || '.svg'}" }`;
    });
    return `// Product catalogue — generated by Pocket Shop Studio v2\nconst PRODUCTS = [\n${items.join(',\n')}\n];\nconst CURRENCY = { label: ${JSON.stringify(currConfig.label)}, tokenId: ${JSON.stringify(currConfig.tokenId)}, icon: ${JSON.stringify(currConfig.icon)} };\n`;
}

function generateInboxConfig(address, pubkey) {
    return `// mInbox - Vendor Configuration
const SHOP_ADDRESS = "0x5452454553484F50";
const VENDOR_ADDRESS = "${address}";
const VENDOR_PUBLIC_KEY = "${pubkey}";

const VENDOR_CONFIG = {
    vendorPublicKey: VENDOR_PUBLIC_KEY,
    vendorAddress: VENDOR_ADDRESS,
    appName: "mInbox",
    version: "2.0.0"
};
`;
}

function generateShopDappConf(shopName, description, currency) {
    const currLabel = currency === 'USDT' ? 'USDT' : 'Minima';
    return JSON.stringify({
        name:        shopName.replace(/[^a-zA-Z0-9 \-]/g, '').trim() || 'Pocket Shop',
        icon:        'icon.svg',
        version:     '2.0.0',
        description: description || `Shop on ${currLabel} — powered by Pocket Shop`,
        category:    'Commerce',
    }, null, '\t');
}

// v1 legacy — still used if caller passes old shape
function generateShopHtml(template, { name, description, price, maxUnits, imageFile, currencyLabel, tokenId, currencyIcon }) {
    return template
        .replace(/\{\{PRODUCT_NAME\}\}/g, name)
        .replace(/\{\{PRODUCT_DESCRIPTION\}\}/g, description)
        .replace(/\{\{PRODUCT_PRICE\}\}/g, price)
        .replace(/\{\{MAX_UNITS\}\}/g, maxUnits)
        .replace(/\{\{PRODUCT_IMAGE\}\}/g, imageFile)
        .replace(/\{\{CURRENCY_LABEL\}\}/g, currencyLabel)
        .replace(/\{\{TOKEN_ID\}\}/g, tokenId)
        .replace(/\{\{CURRENCY_ICON\}\}/g, currencyIcon);
}

async function build(opts, distDir) {
    ensureDir(distDir);

    // Detect v2 (products array) vs v1 (single product)
    const isV2 = Array.isArray(opts.products);
    const shopName = opts.shopName || opts.name || 'Pocket Shop';
    const currency = opts.currency || 'MINI';
    const currConfig = getCurrencyConfig(currency);
    const address = opts.address;
    const pubkey  = opts.pubkey;

    // ── Shop ─────────────────────────────────────────────────────────────────
    const shopTmp = path.join(distDir, `_tmp_shop_${Date.now()}`);
    ensureDir(shopTmp);

    // Files to skip when copying template dir
    const skipFiles = new Set([
        'config.js', 'index.html', 'dapp.conf', 'products.js', 'tree.svg',
        'index.template.html', 'index.template.v2.html'
    ]);

    // Copy template files
    for (const file of fs.readdirSync(SHOP_TEMPLATE_DIR)) {
        if (skipFiles.has(file)) continue;
        if (file === 'product.svg' && isV2) continue; // v2 uses product-N images
        if (file === 'product.svg' && !isV2 && opts.imagePath) continue;
        if (file.startsWith('.')) continue;
        copyFile(path.join(SHOP_TEMPLATE_DIR, file), path.join(shopTmp, file));
    }

    // Generate config.js
    fs.writeFileSync(path.join(shopTmp, 'config.js'), generateShopConfig(address, pubkey, shopName));

    if (isV2) {
        // ── v2 multi-product build ──
        const products = opts.products;

        // Copy product images and annotate with extension
        products.forEach((p, i) => {
            const ext = p.imagePath ? path.extname(p.imagePath) : '.svg';
            p._imageExt = ext;
            const destFile = `product-${i}${ext}`;
            if (p.imagePath && fs.existsSync(p.imagePath)) {
                fs.copyFileSync(p.imagePath, path.join(shopTmp, destFile));
            } else {
                copyFile(DEFAULT_IMAGE, path.join(shopTmp, destFile));
            }
        });

        // Generate products.js
        fs.writeFileSync(path.join(shopTmp, 'products.js'), generateProductsJs(products, currConfig));

        // Generate index.html from v2 template
        const templatePath = path.join(SHOP_TEMPLATE_DIR, 'index.template.v2.html');
        if (!fs.existsSync(templatePath)) throw new Error('index.template.v2.html not found in pocketshop-shop/');
        const template = fs.readFileSync(templatePath, 'utf8');
        const html = template.replace(/\{\{SHOP_NAME\}\}/g, shopName);
        fs.writeFileSync(path.join(shopTmp, 'index.html'), html);

        // Generate dapp.conf
        const desc = opts.description || '';
        fs.writeFileSync(path.join(shopTmp, 'dapp.conf'), generateShopDappConf(shopName, desc, currency));

    } else {
        // ── v1 legacy single-product build ──
        const imageExt  = opts.imagePath ? path.extname(opts.imagePath) : '.svg';
        const imageFile = 'product' + imageExt;

        const templatePath = path.join(SHOP_TEMPLATE_DIR, 'index.template.html');
        if (!fs.existsSync(templatePath)) throw new Error('index.template.html not found in pocketshop-shop/');
        const template = fs.readFileSync(templatePath, 'utf8');
        const html = generateShopHtml(template, {
            name: opts.name, description: opts.description || '', price: opts.price,
            maxUnits: opts.maxUnits || 10, imageFile,
            currencyLabel: currConfig.label, tokenId: currConfig.tokenId, currencyIcon: currConfig.icon
        });
        fs.writeFileSync(path.join(shopTmp, 'index.html'), html);
        fs.writeFileSync(path.join(shopTmp, 'dapp.conf'), generateShopDappConf(opts.name, opts.description, currency));

        if (opts.imagePath && fs.existsSync(opts.imagePath)) {
            fs.copyFileSync(opts.imagePath, path.join(shopTmp, imageFile));
        } else {
            copyFile(DEFAULT_IMAGE, path.join(shopTmp, 'product.svg'));
        }
    }

    const slug = shopName.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
    const shopFile    = slug + '.mds.zip';
    const shopZipPath = path.join(distDir, shopFile);
    const shopSize    = await zipDir(shopTmp, shopZipPath);
    fs.rmSync(shopTmp, { recursive: true, force: true });

    if (shopSize > 50 * 1024) {
        console.warn(`⚠  ${shopFile} is ${(shopSize / 1024).toFixed(1)}KB — exceeds 50KB MiniFS limit`);
    }

    // ── mInbox ────────────────────────────────────────────────────────────────
    const inboxTmp = path.join(distDir, `_tmp_inbox_${Date.now()}`);
    ensureDir(inboxTmp);

    const skipInbox = new Set(['config.js']);
    for (const file of fs.readdirSync(INBOX_TEMPLATE_DIR)) {
        if (skipInbox.has(file)) continue;
        if (file.startsWith('.')) continue;
        copyFile(path.join(INBOX_TEMPLATE_DIR, file), path.join(inboxTmp, file));
    }

    fs.writeFileSync(path.join(inboxTmp, 'config.js'), generateInboxConfig(address, pubkey));

    const inboxFile    = 'mInbox.zip';
    const inboxZipPath = path.join(distDir, inboxFile);
    const inboxSize    = await zipDir(inboxTmp, inboxZipPath);
    fs.rmSync(inboxTmp, { recursive: true, force: true });

    return { shopFile, inboxFile, shopSize, inboxSize };
}

module.exports = { build };
